theme = "catppuccin_mocha"

[editor]
line-number = "relative"
cursorline = true
color-modes = true
bufferline = "multiple"
text-width = 120
soft-wrap = { enable = true }
indent-guides = { render = true }
auto-save = { focus-lost = true }

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner", "file-name", "file-modification-indicator"]
right = ["diagnostics", "selections", "register", "position", "file-type"]
