[[language]]
name = "yaml"
auto-format = true
language-servers = ["yaml-language-server"]
formatter = { command = "yq", args = ["-P"] }

[language-server.yaml-language-server]
command = ".helix/yaml-lsp-wrapper.sh"
config = { yaml = { schemas = { ".helix/recipe-v1.json" = [
  "recipes/recipe.yml",
] } } }

[[language]]
name = "bash"
auto-format = true
formatter = { command = "shfmt", args = ["-i", "4", "-ci"] }
language-servers = ["bash-language-server"]

[[language]]
name = "toml"
auto-format = true
language-servers = ["taplo"]
